### ISSUE TITLE
hephaestus "Formuals" fails on Mac OSX

### ISSUE THREAD

**Issue by ggggggggg** [bruceravel/demeter#18]
![hephaestus](https://cloud.githubusercontent.com/assets/5192577/5907962/943c5bec-a560-11e4-8389-b48c355c71ad.png)
Steps to reproduce:
1. Launch hepaestus from command Line
2. Click Formulas
3. Type anything into the top right entry field (example shows Fe)
4. Hit Enter
I get this error:
Can't call method "SetStatusText" on an undefined value at /opt/local/lib/perl5/site_perl/5.16.3/darwin-thread-multi-2level/Demeter/UI/Hephaestus/Formulas.pm line 248.

It also seems to fail if I hit the "Element" Button, although in a slightly more complex way.  Essentially the GUI locks up, and my cursor can't leave the text entry field.

Version info:
![about hephaestus](https://cloud.githubusercontent.com/assets/5192577/5907969/afb481d8-a560-11e4-989e-e41be0da3a1b.png)
![about this mac](https://cloud.githubusercontent.com/assets/5192577/5908043/48dd9912-a561-11e4-9f28-d8c30c33169c.png)

**Comment by ggggggggg** [comment]
I can confirm that the first failure mode (with the crash) happens on the most recent Windows Version (at least on my pc) as well.  The second failure mode (locked up GUI) doesn't appear to happen on the windows version.

**Comment by bruceravel** [comment]
@ggggggggg,

Does it also fail if you actually enter a value for density?

I don't see either failure on my linux machine here at home.  We have some severe weather going on here in New York state today and tomorrow.  I won't be able to test this on Windows until we are allowed to return to the lab.

And I won't be able to test it on the Mac at all (I don't own one).  So hopefully I'll be able to figure it out from Windows and what you can tell me.

**Comment by ggggggggg** [comment]
On both mac and windows if I type in Density=1 before typing anything in the Formula line it works fine.

**Comment by bruceravel** [comment]
@ggggggggg,

I am finally back after 2 1/2 days of the lab being closed due to a big winter storm.

On my Windows machine, I see that hitting return triggers the error you are seeing.  Clicking the "Compute" button does not.  I'll look into it.  Hopefully, that'll solve the problem on the Mac also.  Thanks for the bug report!

In the future, following [my requested bug reporting procedure](http://bruceravel.github.io/demeter/pods/bugs.pod.html#Capturing_error_messages_from_Demete) is more helpful to me than trying to guess what screenshots I would like to see.  If you do not want to copy the log file into a github issue, you can make [a gist](https://gist.github.com/) from the file.

**Comment by bruceravel** [comment]
Fixed in 7091a8bf514d85bf83373a0e6b5fb278da57fbca

As you can see, this is a one-line fix that you could easily apply on your own machine.

**Comment by ggggggggg** [comment]
I'll try to remember to check out that link if I run into anything new.

**Comment by bruceravel** [comment]
The fix will, of course, be in the next release.
