### ISSUE TITLE
Demeter Cluster size issue

### ISSUE THREAD

**Issue by DetectiveKiwi** [bruceravel/demeter#55]
After running a FEFF calculation with Demeter, "Cluster size" seems to be printing the maximum path length instead of the cluster size.

This occurs when running the commands:
my $atoms = Demeter::Atoms->new(cif => "C:\\[...]\\Cu_mp-30_symmetrized.cif");
 $atoms->set(rpath=>6, rmax=>9);

 my $feff = Demeter::Feff -> new(atoms => $atoms);
 $feff->set(workspace=>"feff/",screen=>0);
 $feff->run;
 print $feff->intrp;

Here's a screenshot of the resulting file:
![feffpaths](https://user-images.githubusercontent.com/25487563/44182559-5bd85480-a0bc-11e8-963a-faf70ec0a34b.png)

The "Cluster size" in the output file is given as 6 while I believe it should output rmax (9 in this case).

I'm running Demeter 0.9.26.

**Comment by bruceravel** [comment]
I think the problem here is one of expectation.  I think things are working as I intended.

"rmax" is the size of the cluster of atoms written to the feff.inp file.

"rpath" is the number used for the RMAX keyword in that feff.inp file.

The ``$feff->intrp`` method happens _after_  the feff.inp file is written and after Feff is run.  Thus the interpretation written by ``intrp`` method observes the RMAX value in feff.inp (and therefore, the rpath value in the Atoms object.  If you look at the feff/feff.inp file that you example script generates, you will see that the cluster in the ATOMS list goes out to 9.

To get the behavior you are going for, you need to set both rmax and rpath to 9.

I sympathize about the confusing nomenclature.  The word "rmax" was historically used in at least two different contexts in the software.  When the Atoms object was modified to treat differently those two particular meanings of the word "rmax", I had to choose a different word for one of the meanings.  So ... it is what it is....

Cheers,
B

**Comment by DetectiveKiwi** [comment]
Gotcha. I was a bit confused by the nomenclature, but I understand it now.

Thanks for the quick response,
John F
