### ISSUE TITLE
Saving XYZ file of cluster from Artemis missing a comment line

### ISSUE THREAD

**Issue by wholden** [bruceravel/demeter#56]
When Artemis is used to export an atomic cluster to XYZ file format, the file is unable to be read in another program (in my case Avogadro).  The reason is that it is missing a blank line.  The second line in the file should be a comment line (per https://en.wikipedia.org/wiki/XYZ_file_format), but this is missing in the saved file from Artemis.  I've been manually adding it.

I'm using Demeter 0.9.25.

**Comment by bruceravel** [comment]
While I won't argue if you say that Avogadro is unhappy with Demeter's output XYZ file, I don't agree that Demeter is writing it incorrectly.  From the XYZ spec: 

      The first line of a step's header is the number of atoms in that step.
      This  integer  may be preceded by whitespace; anything on the line after
      the integer is ignored.  The second line of the header leaves room	for  a
      descriptive  string.   This  line may  be blank, or it may contain some
      information pertinent to that particular step, but it must exist, and  it
      must be just one line long.

If the problem is that Avogadro expects the second line to be blank (which is NOT what the spec requires), then the simplest solution would be to edit the `xyz.tmpl` file (`lib/Demeter/templates/atoms/xyz.tmpl` underneath wherever Demeter is installed on your computer) and replace the line that says `{$A->titles->[0]}` with a blank line.

PS: Using Avogadro 1.2 with OpenBabel 2.3.2, I was able to import a Demetr-produced XYZ file as written.

**Comment by wholden** [comment]
Thanks for the quick reply Bruce!  

In the XYZ file created with my Artemis (0.9.25), the issue is that the atoms start immediately on line 2.  I think Avogadro is not expecting a blank line necessarily, but if I understand the XYZ spec the second line should not contain atom information.

Attached is an xyz file I generated from a cif for Fe2P.
[test.xyz.txt](https://github.com/bruceravel/demeter/files/2484417/test.xyz.txt)

**Comment by wholden** [comment]
I checked my xyz.tmpl file and it doesn't have the `{$A->titles->[0]}` line.  

I see that it is indeed in the GitHub repository with a perhaps fix from a year ago.  I'll pull the latest version.  Thanks again, sorry for the false alarm.

**Comment by bruceravel** [comment]
Or simply put a blank line in the second line of the xyz.tmpl file.
